# Generated by Django 5.2.8 on 2025-11-19 11:45

import devtune.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category_name', models.CharField(max_length=100, verbose_name='Category Name')),
                ('Category_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Category_img', models.ImageField(blank=True, null=True, upload_to=devtune.models.custom_upload_to)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categorys',
            },
        ),
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Chat_session_id', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Chat Name')),
                ('Chat_Active', models.BooleanField(default=False, help_text='Is this Chat Active?', verbose_name='Chat Active')),
                ('Chat_slug', models.SlugField(blank=True, null=True, unique=True)),
                ('Chat_createdat', models.DateTimeField(auto_now_add=True, verbose_name='Chat Created At')),
                ('Chat_utility_params', models.JSONField(blank=True, default=dict, null=True)),
                ('Chat_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='devtune.category')),
                ('Chat_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_owner', to=settings.AUTH_USER_MODEL, verbose_name='Chat Owner')),
            ],
            options={
                'verbose_name': 'Chat',
                'verbose_name_plural': 'Chat',
            },
        ),
    ]
