# Generated by Django 5.2.8 on 2025-11-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtune', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-Chat_createdat'], 'verbose_name': 'Chat', 'verbose_name_plural': 'Chat'},
        ),
        migrations.AddField(
            model_name='category',
            name='Category_description',
            field=models.TextField(blank=True, null=True, verbose_name='Category Description'),
        ),
        migrations.AddField(
            model_name='category',
            name='Category_is_default',
            field=models.BooleanField(default=False, verbose_name='Default Category'),
        ),
        migrations.AddField(
            model_name='chat',
            name='Chat_is_temporary',
            field=models.BooleanField(default=False, help_text='Temporary chat until first message', verbose_name='Is Temporary'),
        ),
        migrations.AddField(
            model_name='chat',
            name='Chat_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Chat Title'),
        ),
    ]
