# Generated by Django 5.2.8 on 2025-11-29 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtune', '0002_alter_category_options_alter_chat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_meta_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
