# Generated by Django 5.2.8 on 2025-11-29 23:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devtune', '0003_category_category_meta_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=300)),
                ('file_path', models.CharField(blank=True, max_length=1024, null=True)),
                ('doc_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('indexed', models.BooleanField(default=False)),
                ('doc_ids', models.JSONField(blank=True, default=list, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_files', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Knowledge File',
                'verbose_name_plural': 'Knowledge Files',
            },
        ),
    ]
